name: Edit Organization README
on: 
    schedule:
        - cron: '0/15 * * * *'
    workflow_dispatch:
    
jobs: 
    update-readme-with-blog: 
        name: Add dev.to Posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "5"
                feed_list: "https://dev.to/feed/dead404code"
                readme_path: "./profile/README.md"
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
          - uses: DeadCodeGames/metrics@replay-clean
            with:
              token: ${{ secrets.READMETOKEN }}
              user: DeadCodeGames
              plugin_languages: yes
              plugin_languages_ignored: CSS, CMake
              plugin_languages_skipped: "metrics"
              plugin_languages_paths_ignored: "DeadCodeGames/Serenify:sqlite"
